export type Theme = 'mexico' | 'usa' | 'argentina'

export const THEMES = {
  mexico: {
    name: 'México',
    emoji: '🇲🇽',
    locale: 'es-MX',
    colors: {
      primary: '#006847',
      secondary: '#D4AF37',
      accent: '#CE1126',
      background: '#0a0f0d',
      text_main: 'rgba(255,255,255,0.97)',
      text_muted: 'rgba(255,255,255,0.78)',
      text_dim: 'rgba(255,255,255,0.42)',
    },
    texts: {
      testMode: 'Modo prueba — los datos no son reales',
      open: 'Abierto',
      locked: 'Bloqueado',
      finished: 'Finalizado',
      live: '● En juego',
      missingPred: 'Falta pronóstico',
      noPlayed: 'No jugaron',
      edit: 'Editar',
      save: 'Guardar',
      cancel: 'Cancelar',
      ranking: 'Ranking',
      rules: 'Reglas',
      matches: 'Partidos',
      profile: 'Perfil',
      you: 'Tú',
      yourPrediction: 'Tu pronóstico actual',
      yourPredLabel: 'Tu pronóstico',
      closesIn: 'Cierra en',
      startsIn: 'Empieza en',
      nextMatch: 'Próximo partido',
      nextSmall: 'Próximo',
      liveNow: '● EN VIVO',
      noPrediction: 'Sin pronóstico',
      back: '← Partidos',
      group: 'Grupo',
      revealWhenLocked: 'Los pronósticos se revelan cuando el partido se bloquee',
      rankingTitle: 'El Ranking',
      rankingSubtitle: 'Desempate: exactos → diferencias → sorteo',
      noPoints: 'Aún no hay puntos registrados',
      exactLabel: 'EXACTO',
      diffLabel: 'DIFERENCIA',
      trendLabel: 'TENDENCIA',
      missLabel: 'FALLO',
    },
    header: null,
  },
  usa: {
    name: 'USA',
    emoji: '🇺🇸',
    locale: 'en-US',
    colors: {
      primary: '#1E3A8A',
      secondary: '#DC2626',
      accent: '#FFFFFF',
      background: '#060912',
      text_main: '#EEF2FF',
      text_muted: '#94A3B8',
      text_dim: '#475569',
    },
    texts: {
      testMode: 'Test Mode — data is not real',
      open: 'Open',
      locked: 'Locked',
      finished: 'Final',
      live: '● In Play',
      missingPred: 'Missing picks',
      noPlayed: 'Did not play',
      edit: 'Edit',
      save: 'Save',
      cancel: 'Cancel',
      ranking: 'Ranking',
      rules: 'Rules',
      matches: 'Matches',
      profile: 'Profile',
      you: 'You',
      yourPrediction: 'Your current pick',
      yourPredLabel: 'Your pick',
      closesIn: 'Closes in',
      startsIn: 'Starts in',
      nextMatch: 'Next match',
      nextSmall: 'Next',
      liveNow: '● LIVE',
      noPrediction: 'No pick',
      back: '← Matches',
      group: 'Group',
      revealWhenLocked: 'Picks are revealed when the match locks',
      rankingTitle: 'Leaderboard',
      rankingSubtitle: 'Tiebreaker: exact → diff → draw',
      noPoints: 'No points yet',
      exactLabel: 'EXACT',
      diffLabel: 'DIFF',
      trendLabel: 'TREND',
      missLabel: 'MISS',
    },
    header: 'FREEDOM',
  },
  argentina: {
    name: 'Argentina',
    emoji: '🇦🇷',
    locale: 'es-AR',
    colors: {
      primary: '#29ABE2',
      secondary: '#F5C100',
      accent: '#F5C100',
      background: '#08101A',
      text_main: '#F0FAFF',
      text_muted: '#7FB3CC',
      text_dim: '#3A6A8A',
    },
    texts: {
      testMode: 'Modo de prueba — los datos no son reales',
      open: 'Abierto boludo',
      locked: 'Se cierra',
      finished: 'Terminó',
      live: '¡Dale, en vivo!',
      missingPred: 'Che, ¿dónde estás?',
      noPlayed: 'No se dejaron de joder',
      edit: 'Che, editar',
      save: 'Listo, guardá',
      cancel: 'Nah',
      ranking: 'El ranking',
      rules: 'Las reglas',
      matches: 'Los partidos',
      profile: 'El perfil',
      you: 'Vos',
      yourPrediction: 'Tu pronóstico actual',
      yourPredLabel: 'Tu pronóstico',
      closesIn: 'Se cierra en',
      startsIn: 'Empieza en',
      nextMatch: 'El próximo',
      nextSmall: 'Próximo',
      liveNow: '● ¡EN VIVO!',
      noPrediction: 'Sin pronóstico',
      back: '← Los partidos',
      group: 'Grupo',
      revealWhenLocked: 'Los pronósticos se muestran cuando el partido se bloquee',
      rankingTitle: 'El Ranking',
      rankingSubtitle: 'Desempate: exactos → diferencias → sorteo',
      noPoints: 'Todavía no hay puntos, papá',
      exactLabel: 'EXACTO',
      diffLabel: 'DIFERENCIA',
      trendLabel: 'TENDENCIA',
      missLabel: 'FALLASTE',
    },
    header: null,
  },
}

export function getTheme(theme: Theme = 'mexico') {
  return THEMES[theme] || THEMES.mexico
}
