export type Theme = 'mexico' | 'mexico_dia' | 'usa' | 'usa_dia' | 'argentina' | 'argentina_dia'

export const THEMES: Record<Theme, {
  name: string
  emoji: string
  locale: string
  mode: 'dark' | 'light'
  colors: Record<string, string>
  pattern: string
  texts: Record<string, string>
  header: string | null
}> = {
  mexico: {
    name: 'México',
    emoji: '🇲🇽',
    locale: 'es-MX',
    mode: 'dark',
    colors: {
      primary: '#007850',
      secondary: '#D4AF37',
      accent: '#CE1126',
      background: '#0a0f0d',
      text_main: 'rgba(255,255,255,0.97)',
      text_muted: 'rgba(255,255,255,0.78)',
      text_dim: 'rgba(255,255,255,0.42)',
    },
    pattern: [
      'repeating-linear-gradient(135deg, rgba(0,104,71,0.055) 0, rgba(0,104,71,0.055) 1px, transparent 1px, transparent 28px)',
      'repeating-linear-gradient(-135deg, rgba(206,17,38,0.035) 0, rgba(206,17,38,0.035) 1px, transparent 1px, transparent 28px)',
    ].join(', '),
    texts: {
      testMode: 'Modo prueba — los datos no son reales',
      open: 'Abierto', locked: 'Bloqueado', finished: 'Finalizado', live: '● En juego',
      missingPred: 'Falta pronóstico', noPlayed: 'No jugaron',
      edit: 'Editar', save: 'Guardar', cancel: 'Cancelar',
      ranking: 'Ranking', rules: 'Reglas', matches: 'Partidos', profile: 'Perfil',
      you: 'Tú', yourPrediction: 'Tu pronóstico actual', yourPredLabel: 'Tu pronóstico',
      closesIn: 'Cierra en', startsIn: 'Empieza en', nextMatch: 'Próximo partido', nextSmall: 'Próximo',
      liveNow: '● EN VIVO', noPrediction: 'Sin pronóstico', back: '← Partidos', group: 'Grupo',
      revealWhenLocked: 'Los pronósticos se revelan cuando el partido se bloquee',
      rankingTitle: 'El Ranking', rankingSubtitle: 'Desempate: exactos → diferencias → sorteo',
      noPoints: 'Aún no hay puntos registrados',
      exactLabel: 'EXACTO', diffLabel: 'DIFERENCIA', trendLabel: 'TENDENCIA', missLabel: 'FALLO',
    },
    header: null,
  },
  mexico_dia: {
    name: 'México',
    emoji: '🇲🇽',
    locale: 'es-MX',
    mode: 'light',
    colors: {
      primary: '#006847',
      secondary: '#A8870F',
      accent: '#CE1126',
      background: '#F0F7F3',
      text_main: 'rgba(0,0,0,0.87)',
      text_muted: 'rgba(0,0,0,0.56)',
      text_dim: 'rgba(0,0,0,0.48)',
    },
    pattern: [
      'repeating-linear-gradient(135deg, rgba(0,104,71,0.07) 0, rgba(0,104,71,0.07) 1px, transparent 1px, transparent 28px)',
      'repeating-linear-gradient(-135deg, rgba(206,17,38,0.045) 0, rgba(206,17,38,0.045) 1px, transparent 1px, transparent 28px)',
    ].join(', '),
    texts: {
      testMode: 'Modo prueba — los datos no son reales',
      open: 'Abierto', locked: 'Bloqueado', finished: 'Finalizado', live: '● En juego',
      missingPred: 'Falta pronóstico', noPlayed: 'No jugaron',
      edit: 'Editar', save: 'Guardar', cancel: 'Cancelar',
      ranking: 'Ranking', rules: 'Reglas', matches: 'Partidos', profile: 'Perfil',
      you: 'Tú', yourPrediction: 'Tu pronóstico actual', yourPredLabel: 'Tu pronóstico',
      closesIn: 'Cierra en', startsIn: 'Empieza en', nextMatch: 'Próximo partido', nextSmall: 'Próximo',
      liveNow: '● EN VIVO', noPrediction: 'Sin pronóstico', back: '← Partidos', group: 'Grupo',
      revealWhenLocked: 'Los pronósticos se revelan cuando el partido se bloquee',
      rankingTitle: 'El Ranking', rankingSubtitle: 'Desempate: exactos → diferencias → sorteo',
      noPoints: 'Aún no hay puntos registrados',
      exactLabel: 'EXACTO', diffLabel: 'DIFERENCIA', trendLabel: 'TENDENCIA', missLabel: 'FALLO',
    },
    header: null,
  },
  usa: {
    name: 'USA',
    emoji: '🇺🇸',
    locale: 'en-US',
    mode: 'dark',
    colors: {
      primary: '#3B82F6',
      secondary: '#DC2626',
      accent: '#DC2626',
      background: '#050D1E',
      text_main: '#EEF2FF',
      text_muted: '#94A3B8',
      text_dim: '#5C7189',
    },
    pattern: 'repeating-linear-gradient(180deg, rgba(220,38,38,0.11) 0, rgba(220,38,38,0.11) 6px, transparent 6px, transparent 24px)',
    texts: {
      testMode: 'Test Mode — data is not real',
      open: 'Open', locked: 'Locked', finished: 'Final', live: '● In Play',
      missingPred: 'Missing picks', noPlayed: 'Did not play',
      edit: 'Edit', save: 'Save', cancel: 'Cancel',
      ranking: 'Ranking', rules: 'Rules', matches: 'Matches', profile: 'Profile',
      you: 'You', yourPrediction: 'Your current pick', yourPredLabel: 'Your pick',
      closesIn: 'Closes in', startsIn: 'Starts in', nextMatch: 'Next match', nextSmall: 'Next',
      liveNow: '● LIVE', noPrediction: 'No pick', back: '← Matches', group: 'Group',
      revealWhenLocked: 'Picks are revealed when the match locks',
      rankingTitle: 'Leaderboard', rankingSubtitle: 'Tiebreaker: exact → diff → draw',
      noPoints: 'No points yet',
      exactLabel: 'EXACT', diffLabel: 'DIFF', trendLabel: 'TREND', missLabel: 'MISS',
    },
    header: 'FREEDOM',
  },
  usa_dia: {
    name: 'USA',
    emoji: '🇺🇸',
    locale: 'en-US',
    mode: 'light',
    colors: {
      primary: '#1E3A8A',
      secondary: '#B91C1C',
      accent: '#1E3A8A',
      background: '#FFFFFF',
      text_main: 'rgba(0,0,0,0.87)',
      text_muted: 'rgba(0,0,0,0.54)',
      text_dim: 'rgba(0,0,0,0.45)',
    },
    pattern: 'repeating-linear-gradient(180deg, rgba(185,28,28,0.45) 0, rgba(185,28,28,0.45) 18px, transparent 18px, transparent 72px)',
    texts: {
      testMode: 'Test Mode — data is not real',
      open: 'Open', locked: 'Locked', finished: 'Final', live: '● In Play',
      missingPred: 'Missing picks', noPlayed: 'Did not play',
      edit: 'Edit', save: 'Save', cancel: 'Cancel',
      ranking: 'Ranking', rules: 'Rules', matches: 'Matches', profile: 'Profile',
      you: 'You', yourPrediction: 'Your current pick', yourPredLabel: 'Your pick',
      closesIn: 'Closes in', startsIn: 'Starts in', nextMatch: 'Next match', nextSmall: 'Next',
      liveNow: '● LIVE', noPrediction: 'No pick', back: '← Matches', group: 'Group',
      revealWhenLocked: 'Picks are revealed when the match locks',
      rankingTitle: 'Leaderboard', rankingSubtitle: 'Tiebreaker: exact → diff → draw',
      noPoints: 'No points yet',
      exactLabel: 'EXACT', diffLabel: 'DIFF', trendLabel: 'TREND', missLabel: 'MISS',
    },
    header: 'FREEDOM',
  },
  argentina: {
    name: 'Argentina',
    emoji: '🇦🇷',
    locale: 'es-AR',
    mode: 'dark',
    colors: {
      primary: '#29ABE2',
      secondary: '#F5C100',
      accent: '#F5C100',
      background: '#08101A',
      text_main: '#F0FAFF',
      text_muted: '#7FB3CC',
      text_dim: '#3A6A8A',
    },
    pattern: 'repeating-linear-gradient(90deg, transparent 0, transparent 36px, rgba(41,171,226,0.05) 36px, rgba(41,171,226,0.05) 72px)',
    texts: {
      testMode: 'Modo de prueba — los datos no son reales',
      open: 'Abierto boludo', locked: 'Se cierra', finished: 'Terminó', live: '¡Dale, en vivo!',
      missingPred: 'Che, ¿dónde estás?', noPlayed: 'No se dejaron de joder',
      edit: 'Che, editar', save: 'Listo, guardá', cancel: 'Nah',
      ranking: 'El ranking', rules: 'Las reglas', matches: 'Los partidos', profile: 'El perfil',
      you: 'Vos', yourPrediction: 'Tu pronóstico actual', yourPredLabel: 'Tu pronóstico',
      closesIn: 'Se cierra en', startsIn: 'Empieza en', nextMatch: 'El próximo', nextSmall: 'Próximo',
      liveNow: '● ¡EN VIVO!', noPrediction: 'Sin pronóstico', back: '← Los partidos', group: 'Grupo',
      revealWhenLocked: 'Los pronósticos se muestran cuando el partido se bloquee',
      rankingTitle: 'El Ranking', rankingSubtitle: 'Desempate: exactos → diferencias → sorteo',
      noPoints: 'Todavía no hay puntos, papá',
      exactLabel: 'EXACTO', diffLabel: 'DIFERENCIA', trendLabel: 'TENDENCIA', missLabel: 'FALLASTE',
    },
    header: null,
  },
  argentina_dia: {
    name: 'Argentina',
    emoji: '🇦🇷',
    locale: 'es-AR',
    mode: 'light',
    colors: {
      primary: '#0070B8',
      secondary: '#F5C100',
      accent: '#F5C100',
      background: '#EEF8FF',
      text_main: 'rgba(0,0,0,0.87)',
      text_muted: 'rgba(0,0,0,0.56)',
      text_dim: 'rgba(0,0,0,0.48)',
    },
    pattern: 'repeating-linear-gradient(90deg, transparent 0, transparent 36px, rgba(0,112,184,0.10) 36px, rgba(0,112,184,0.10) 72px)',
    texts: {
      testMode: 'Modo de prueba — los datos no son reales',
      open: 'Abierto boludo', locked: 'Se cierra', finished: 'Terminó', live: '¡Dale, en vivo!',
      missingPred: 'Che, ¿dónde estás?', noPlayed: 'No se dejaron de joder',
      edit: 'Editar', save: 'Guardar', cancel: 'Nah',
      ranking: 'El ranking', rules: 'Las reglas', matches: 'Los partidos', profile: 'El perfil',
      you: 'Vos', yourPrediction: 'Tu pronóstico actual', yourPredLabel: 'Tu pronóstico',
      closesIn: 'Se cierra en', startsIn: 'Empieza en', nextMatch: 'El próximo', nextSmall: 'Próximo',
      liveNow: '● ¡EN VIVO!', noPrediction: 'Sin pronóstico', back: '← Los partidos', group: 'Grupo',
      revealWhenLocked: 'Los pronósticos se muestran cuando el partido se bloquee',
      rankingTitle: 'El Ranking', rankingSubtitle: 'Desempate: exactos → diferencias → sorteo',
      noPoints: 'Todavía no hay puntos, papá',
      exactLabel: 'EXACTO', diffLabel: 'DIFERENCIA', trendLabel: 'TENDENCIA', missLabel: 'FALLASTE',
    },
    header: null,
  },
}

export function getTheme(theme: Theme = 'mexico') {
  return THEMES[theme] || THEMES.mexico
}
